networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

services:
  db:
    image: mysql:8.0
    container_name: rails_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_volumes:/var/lib/mysql
    env_file:
      - .env
    networks:
       - my_network

  api:
    container_name: rails_api
    image: minshif
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&  bundle install && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - .:/minshif
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
       - my_network

  sidekiq:
    container_name: sidekiq
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/minshif
    depends_on:
      - db
      - redis
    networks:
      - my_network

  redis:
    container_name: redis
    image: "redis:7.0-alpine"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  mysql_volumes:
  redis_volume:
